In [1]:
import numpy as np

In [2]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
# Sum by column
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
# Calculate percentage 
percentage = 100 * A/cal.reshape(1,4)

In [5]:
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## Python/numpy vectors

In [6]:
# Rank 1 array - Not recommended
a = np.random.randn(5)

In [7]:
print(a)

[ 1.05621607 -0.92920134 -1.45371267  1.76549977 -0.86470044]


In [8]:
print(a.shape)

(5,)


In [9]:
print(a.T)

[ 1.05621607 -0.92920134 -1.45371267  1.76549977 -0.86470044]


In [10]:
print(np.dot(a,a.T))

7.956984328575527


In [11]:
# Recommended
a = np.random.randn(5,1)

In [12]:
print(a)

[[-0.00761484]
 [-0.06826989]
 [ 0.3522642 ]
 [-1.00750038]
 [ 1.41691139]]


In [16]:
print(a.shape)

(5, 1)


In [13]:
print(a.T)

[[-0.00761484 -0.06826989  0.3522642  -1.00750038  1.41691139]]


In [17]:
print(a.T.shape)

(1, 5)


In [14]:
print(np.dot(a, a.T))

[[ 5.79857385e-05  5.19864070e-04 -2.68243439e-03  7.67195093e-03
  -1.07895489e-02]
 [ 5.19864070e-04  4.66077795e-03 -2.40490385e-02  6.87819408e-02
  -9.67323852e-02]
 [-2.68243439e-03 -2.40490385e-02  1.24090068e-01 -3.54906319e-01
   4.99127159e-01]
 [ 7.67195093e-03  6.87819408e-02 -3.54906319e-01  1.01505702e+00
  -1.42753876e+00]
 [-1.07895489e-02 -9.67323852e-02  4.99127159e-01 -1.42753876e+00
   2.00763788e+00]]


In [18]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [19]:
a = np.array([[2,1], [1,3]])
np.dot(a,a)

array([[ 5,  5],
       [ 5, 10]])

In [27]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45)

c = np.dot(a,b)
c.shape

(12288, 45)

In [22]:
a = np.array([[1,1], [1,-1]])
b = np.array([[2], [3]])
a+b

array([[3, 3],
       [4, 2]])